<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>

<!DOCTYPE html>
<html>
<head>
<%@ include file="../head.jsp" %>
</head>
<style>
	.nav-item {
		margin: 0px 5px;
	}
</style>
<body>
	<% try {
		if (session.getAttribute("loggedIn") == null || !((Boolean)session.getAttribute("loggedIn"))) {
			response.sendRedirect("../login.jsp");
		} else {
			if (session.getAttribute("isAdmin") != null && (Integer)session.getAttribute("isAdmin") == 1) { %>	
				<%@ include file="../header.jsp" %>
				<div class="container mt-3">
					<h1>Welcome <%= session.getAttribute("username") %> </h1>
					<p class="text-muted"> <%= session.getAttribute("ssn") %></p>
					<ul class="nav">
					  <li class="nav-item">
					    <a href="../employee/employees.jsp">Manage Employees</a>
					  </li>
					  <li class="nav-item">
					    <a href="reservations.jsp">See Reservations</a>
					  </li>
					  <li class="nav-item">
					  	<a href="report.jsp">Sales Report</a>
					  </li>
					</ul>
					
					<% 
						ApplicationDB db = new ApplicationDB();	
						Connection con = db.getConnection();		
					%>
					<div class="row">
						<div class="col-md-6">
							<hr>
							<div class="card">
								<div class="card-body">
								<% 
									Statement getTopCustomer = con.createStatement();
									String topCustomerStmt = "select c.email_address, c.username, c.first_name, c.last_name, sum(r.total_fare) revenue ";
											topCustomerStmt += "from Customers c, Reservations r ";
											topCustomerStmt += "where c.email_address = r.email_address ";
											topCustomerStmt += "group by c.email_address ";
											topCustomerStmt += "order by revenue desc ";
											topCustomerStmt += "limit 1;";
									ResultSet topCustomer = getTopCustomer.executeQuery(topCustomerStmt);
								%>
									<h4>#1 Customer*</h4>
									<% if (topCustomer.next()) {%>
									<table class="table">
										<thead>
											<tr>
										    	<th scope="col">Username</th>
										    	<th scope="col">Total Revenue</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>
													<%= topCustomer.getString("username") %>
												</td>
												<td id="topCustomerRevenue">
													<%= topCustomer.getFloat("revenue") %>
												</td>
											</tr>
										</tbody>
									</table>
									<% } else { %>
										<div class="alert alert-secondary">No Customers Generating Revenue Yet</div>
									<% } 
										topCustomer.close();
										getTopCustomer.close();
									%>
									<div class="text-muted">*Total Revenue generated by a customer for all time</div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<hr>
							<div class="card">
								<div class="card-body">
									<h4>Top 5 Active Transit Lines (Monthly*)</h4>
									<form action="dashboard.jsp" method="post">
										<div class="input-group">
											<select class="form-control" name="month">
												<option disabled selected>Select Month</option>
												<option>January</option>
												<option>February</option>
												<option>March</option>
												<option>April</option>
												<option>May</option>
												<option>June</option>
												<option>July</option>
												<option>August</option>
												<option>September</option>
												<option>October</option>
												<option>November</option>
												<option>December</option>
											</select>
											<div class="input-group-append">
												<input class="btn btn-primary" type="submit" value="Submit">
											</div>
										</div>
									</form>
									<%	
									if (request.getParameter("month") != null) {
										
										String topActiveLinesStmt = "select s.transit_name, count(*) reservations_made ";
											topActiveLinesStmt += "from Schedules s, Reservations r ";
											topActiveLinesStmt += "where s.schedule_id = r.schedule_id ";
											topActiveLinesStmt += "and monthname(reserved_on) = ?";
											topActiveLinesStmt += "group by s.transit_name ";
											topActiveLinesStmt += "order by reservations_made desc limit 5";
											
										PreparedStatement getTopActiveLines = con.prepareStatement(topActiveLinesStmt);
										getTopActiveLines.setString(1, request.getParameter("month"));
										ResultSet topActiveLines = getTopActiveLines.executeQuery();
										
										if (topActiveLines.next()) { %>
										<table class="table">
										<thead>
											<tr>
												<th scope="col">#</th>
										    	<th scope="col">Transit Lines</th>
										    	<th>Total <%= request.getParameter("month") %> Reservations</th>
											</tr>
										</thead>
										<tbody>
											<%
											int i = 1;
											do { %>
												<tr>
													<td>
														<%= i %>
													</td>
													<td>
														<%= topActiveLines.getString("transit_name") %>
													</td>
													<td>
														<%= topActiveLines.getInt("reservations_made") %>
													</td>
												</tr>
											<%	i++;
											} while (topActiveLines.next()); %>
										</tbody>
									</table>
										
									<% 	} else { %>
											<div class="alert alert-secondary">No Reservations made this month.</div>
									<%
										}
									} 
									%>
									
								
									<div class="form-text text-muted">*Aggregate data for each month.</div>
									<div class="form-text text-muted">Activity based on when the reservation was made.</div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<hr>
							<div class="card">
								<div class="card-body">
									<%
										Statement getUsernames = con.createStatement();
										ResultSet usernames = getUsernames.executeQuery("Select username from Customers");
									%>
									<h4>Total Revenue By Customer</h4>
									<% if (usernames.next()) { %>
										<form action="dashboard.jsp" method="post">
											<div class="input-group">
												<select class="form-control" name="username">
													<option disabled selected>Select a User</option>
													<% do { %>
														<option><%= usernames.getString("username") %></option>
													<% } while(usernames.next()); %>
												</select>
												<div class="input-group-append">
													<input class="btn btn-primary" type="submit" value="Submit">
												</div>
											</div>
										</form>
										<%
											getUsernames.close();
											usernames.close();
										%>
										
										<% if (request.getParameter("username") != null) { %>
											<br>
											<h5> Revenue for <%= request.getParameter("username") %> </h5>
												<%
													String getRevenueStmt = "select c.email_address, c.username, c.first_name, c.last_name, sum(r.total_fare) as revenue ";
													getRevenueStmt += "from Customers c, Reservations r ";
													getRevenueStmt += "where c.email_address = r.email_address ";
													getRevenueStmt += "and c.username = ? ";
													getRevenueStmt += "group by c.email_address;";
													
													PreparedStatement getRevenue = con.prepareStatement(getRevenueStmt);
													getRevenue.setString(1, request.getParameter("username"));
													ResultSet revenue = getRevenue.executeQuery();
												%>
											
												<% if (revenue.next()) { %>
													<p>Total: 
														<span id="customerRevenue"><%= revenue.getFloat("revenue") %>
														</span>
													</p>
												<% } else { %>
													<div class="alert alert-secondary">No Revenue for this Customer</div>
												<% } %>
												<%
													getRevenue.close();
													revenue.close();
												%>
										<% } %>
									<% } else { %>
										<div class="alert alert-secondary">No Customers Available</div>
									<% } 
									
									%>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<hr>
							<div class="card">
								<div class="card-body">
									<%
										Statement getTransitLines = con.createStatement();
										ResultSet transitLines = getTransitLines.executeQuery("Select transit_name from TransitLines");
									%>
									<h4>Total Revenue By Transit Line</h4>
									<% if (transitLines.next()) { %>
										<form action="dashboard.jsp" method="post">
											<div class="input-group">
												<select class="form-control" name="transitLine">
													<option disabled selected>Select Transit Line</option>
													<% do { %>
														<option><%= transitLines.getString("transit_name") %></option>
													<% } while(transitLines.next()); %>
												</select>
												<div class="input-group-append">
													<input class="btn btn-primary" type="submit" value="Submit">
												</div>
											</div>
										</form>
										<%
											getTransitLines.close();
											transitLines.close();
										%>
										<% if (request.getParameter("transitLine") != null) { %>
											<br>
											<h5> Revenue for <%= request.getParameter("transitLine") %> </h5>
												<%
													String getRevenueStmt = "select s.transit_name, sum(r.total_fare) as revenue ";
													getRevenueStmt += "from Schedules s,  Reservations r ";
													getRevenueStmt += "where s.schedule_id = r.schedule_id ";
													getRevenueStmt += "and s.transit_name = ? ";
													getRevenueStmt += "group by s.transit_name;";
													
													PreparedStatement getRevenue = con.prepareStatement(getRevenueStmt);
													getRevenue.setString(1, request.getParameter("transitLine"));
													ResultSet revenue = getRevenue.executeQuery();
												%>
											
												<% if (revenue.next()) { %>
													<p>Total: 
														<span id="transitRevenue"><%= revenue.getFloat("revenue") %>
														</span>
													</p>
												<% } else { %>
													<div class="alert alert-secondary">No Revenue for this Transit Line</div>
												<% } %>
												<%
													getRevenue.close();
													revenue.close();
												%>
										<% } %>
									<% } else { %>
										<div class="alert alert-secondary">No Transit Lines Available</div>
									<% } 
										con.close();
									%>
								</div>
							</div>
						</div>
					</div>
				</div>
		<% 
				} else {
					response.sendRedirect("../index.jsp");
				}
			}
		} catch (Exception e) {
		 	out.print(e);
	 	} %>
					
<script>
	var rev = document.getElementById("topCustomerRevenue");
	rev.textContent = currencyFormat(rev.textContent);
	
	var rev2 = document.getElementById("customerRevenue");
	 
	if (rev2 !== null) {
		rev2.textContent = currencyFormat(rev2.textContent);
	}
	
	var rev3 = document.getElementById("transitRevenue");
	
	if (rev3 !== null) {
		rev3.textContent = currencyFormat(rev3.textContent);
	}
	
	function currencyFormat(txt) {
		return '$'+parseFloat(txt).toFixed(2);
	}
</script>
</body>
</html>
					